### ISSUE TITLE
IMPROVE CONTAINER UI

### ISSUE THREAD

**Issue by stezh** [CognitiveCanvas/CognitiveCanvas-Container#35]
This is a general issue to collect people's idea about improvement of container UI. (Please edit this if you want to add new ideas).

- [x] Top bar should not be moved when user scroll down the page. 
- [x] Workflow of people edit the name of the map
- [x] Icon to back to map management page from map

parent to #9
parent to #12
